name: GetScreen Windows (6H)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Downloading & Setting Up
        shell: pwsh
        run: |
          $content = "EMAIL_SECRET=zeshan.bwptrade52@gmail.com"
          Out-File -FilePath secrets.txt -InputObject $content -Encoding utf8
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/gdzoens68gz1o4wuwtf0x/down.bat?rlkey=wd1ecn33dv9yn2uvdyynavbs6&dl=1" -OutFile "down.bat"
          cmd /c down.bat

      - name: Time Counter
        shell: pwsh
        run: |
          python time.py
